[package]
name = "minesweeper-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
gloo-console = "0.3.0"
wasm-bindgen = "0.2.87"
rand = "0.8.5"